// Code generated by protoc-gen-go. DO NOT EDIT.
// source: catalog.proto

package catalog

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PhoneType int32

const (
	PhoneType_WORK   PhoneType = 0
	PhoneType_MOBILE PhoneType = 1
)

var PhoneType_name = map[int32]string{
	0: "WORK",
	1: "MOBILE",
}

var PhoneType_value = map[string]int32{
	"WORK":   0,
	"MOBILE": 1,
}

func (x PhoneType) String() string {
	return proto.EnumName(PhoneType_name, int32(x))
}

func (PhoneType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{0}
}

type Tags struct {
	Tag                  []*Tag   `protobuf:"bytes,1,rep,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tags) Reset()         { *m = Tags{} }
func (m *Tags) String() string { return proto.CompactTextString(m) }
func (*Tags) ProtoMessage()    {}
func (*Tags) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{0}
}

func (m *Tags) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tags.Unmarshal(m, b)
}
func (m *Tags) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tags.Marshal(b, m, deterministic)
}
func (m *Tags) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tags.Merge(m, src)
}
func (m *Tags) XXX_Size() int {
	return xxx_messageInfo_Tags.Size(m)
}
func (m *Tags) XXX_DiscardUnknown() {
	xxx_messageInfo_Tags.DiscardUnknown(m)
}

var xxx_messageInfo_Tags proto.InternalMessageInfo

func (m *Tags) GetTag() []*Tag {
	if m != nil {
		return m.Tag
	}
	return nil
}

type Tag struct {
	TagName              string   `protobuf:"bytes,1,opt,name=tagName,proto3" json:"tagName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{1}
}

func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetTagName() string {
	if m != nil {
		return m.TagName
	}
	return ""
}

// Item in a inventory of an area
type Item struct {
	Tag                  []*Tag      `protobuf:"bytes,1,rep,name=tag,proto3" json:"tag,omitempty"`
	ProductName          string      `protobuf:"bytes,2,opt,name=productName,proto3" json:"productName,omitempty"`
	Id                   []byte      `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	ImageResource        string      `protobuf:"bytes,4,opt,name=imageResource,proto3" json:"imageResource,omitempty"`
	Size                 string      `protobuf:"bytes,5,opt,name=size,proto3" json:"size,omitempty"`
	State                *StockState `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{2}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetTag() []*Tag {
	if m != nil {
		return m.Tag
	}
	return nil
}

func (m *Item) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

func (m *Item) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Item) GetImageResource() string {
	if m != nil {
		return m.ImageResource
	}
	return ""
}

func (m *Item) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func (m *Item) GetState() *StockState {
	if m != nil {
		return m.State
	}
	return nil
}

type StockState struct {
	OriginalStockLevel       int32                `protobuf:"varint,1,opt,name=originalStockLevel,proto3" json:"originalStockLevel,omitempty"`
	CurrentStockLevel        int32                `protobuf:"varint,2,opt,name=currentStockLevel,proto3" json:"currentStockLevel,omitempty"`
	LastRestock              *timestamp.Timestamp `protobuf:"bytes,3,opt,name=lastRestock,proto3" json:"lastRestock,omitempty"`
	LastPrice                float32              `protobuf:"fixed32,4,opt,name=lastPrice,proto3" json:"lastPrice,omitempty"`
	StockWaitingToBeReceived int32                `protobuf:"varint,5,opt,name=stockWaitingToBeReceived,proto3" json:"stockWaitingToBeReceived,omitempty"`
	Justification            *Justification       `protobuf:"bytes,6,opt,name=justification,proto3" json:"justification,omitempty"`
	LastProvider             *Provider            `protobuf:"bytes,7,opt,name=lastProvider,proto3" json:"lastProvider,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}             `json:"-"`
	XXX_unrecognized         []byte               `json:"-"`
	XXX_sizecache            int32                `json:"-"`
}

func (m *StockState) Reset()         { *m = StockState{} }
func (m *StockState) String() string { return proto.CompactTextString(m) }
func (*StockState) ProtoMessage()    {}
func (*StockState) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{3}
}

func (m *StockState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockState.Unmarshal(m, b)
}
func (m *StockState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockState.Marshal(b, m, deterministic)
}
func (m *StockState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockState.Merge(m, src)
}
func (m *StockState) XXX_Size() int {
	return xxx_messageInfo_StockState.Size(m)
}
func (m *StockState) XXX_DiscardUnknown() {
	xxx_messageInfo_StockState.DiscardUnknown(m)
}

var xxx_messageInfo_StockState proto.InternalMessageInfo

func (m *StockState) GetOriginalStockLevel() int32 {
	if m != nil {
		return m.OriginalStockLevel
	}
	return 0
}

func (m *StockState) GetCurrentStockLevel() int32 {
	if m != nil {
		return m.CurrentStockLevel
	}
	return 0
}

func (m *StockState) GetLastRestock() *timestamp.Timestamp {
	if m != nil {
		return m.LastRestock
	}
	return nil
}

func (m *StockState) GetLastPrice() float32 {
	if m != nil {
		return m.LastPrice
	}
	return 0
}

func (m *StockState) GetStockWaitingToBeReceived() int32 {
	if m != nil {
		return m.StockWaitingToBeReceived
	}
	return 0
}

func (m *StockState) GetJustification() *Justification {
	if m != nil {
		return m.Justification
	}
	return nil
}

func (m *StockState) GetLastProvider() *Provider {
	if m != nil {
		return m.LastProvider
	}
	return nil
}

type Justification struct {
	Text                 string               `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Employee             *Employee            `protobuf:"bytes,2,opt,name=employee,proto3" json:"employee,omitempty"`
	PostedOn             *timestamp.Timestamp `protobuf:"bytes,3,opt,name=postedOn,proto3" json:"postedOn,omitempty"`
	History              []*EditHistory       `protobuf:"bytes,4,rep,name=history,proto3" json:"history,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Justification) Reset()         { *m = Justification{} }
func (m *Justification) String() string { return proto.CompactTextString(m) }
func (*Justification) ProtoMessage()    {}
func (*Justification) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{4}
}

func (m *Justification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Justification.Unmarshal(m, b)
}
func (m *Justification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Justification.Marshal(b, m, deterministic)
}
func (m *Justification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Justification.Merge(m, src)
}
func (m *Justification) XXX_Size() int {
	return xxx_messageInfo_Justification.Size(m)
}
func (m *Justification) XXX_DiscardUnknown() {
	xxx_messageInfo_Justification.DiscardUnknown(m)
}

var xxx_messageInfo_Justification proto.InternalMessageInfo

func (m *Justification) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Justification) GetEmployee() *Employee {
	if m != nil {
		return m.Employee
	}
	return nil
}

func (m *Justification) GetPostedOn() *timestamp.Timestamp {
	if m != nil {
		return m.PostedOn
	}
	return nil
}

func (m *Justification) GetHistory() []*EditHistory {
	if m != nil {
		return m.History
	}
	return nil
}

type EditHistory struct {
	Text                 string               `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	LastEdit             *timestamp.Timestamp `protobuf:"bytes,2,opt,name=lastEdit,proto3" json:"lastEdit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *EditHistory) Reset()         { *m = EditHistory{} }
func (m *EditHistory) String() string { return proto.CompactTextString(m) }
func (*EditHistory) ProtoMessage()    {}
func (*EditHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{5}
}

func (m *EditHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditHistory.Unmarshal(m, b)
}
func (m *EditHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditHistory.Marshal(b, m, deterministic)
}
func (m *EditHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditHistory.Merge(m, src)
}
func (m *EditHistory) XXX_Size() int {
	return xxx_messageInfo_EditHistory.Size(m)
}
func (m *EditHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_EditHistory.DiscardUnknown(m)
}

var xxx_messageInfo_EditHistory proto.InternalMessageInfo

func (m *EditHistory) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *EditHistory) GetLastEdit() *timestamp.Timestamp {
	if m != nil {
		return m.LastEdit
	}
	return nil
}

type Employee struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string         `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	EmployeeCode         string         `protobuf:"bytes,3,opt,name=employeeCode,proto3" json:"employeeCode,omitempty"`
	PhoneNumber          []*PhoneNumber `protobuf:"bytes,5,rep,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Employee) Reset()         { *m = Employee{} }
func (m *Employee) String() string { return proto.CompactTextString(m) }
func (*Employee) ProtoMessage()    {}
func (*Employee) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{6}
}

func (m *Employee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Employee.Unmarshal(m, b)
}
func (m *Employee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Employee.Marshal(b, m, deterministic)
}
func (m *Employee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Employee.Merge(m, src)
}
func (m *Employee) XXX_Size() int {
	return xxx_messageInfo_Employee.Size(m)
}
func (m *Employee) XXX_DiscardUnknown() {
	xxx_messageInfo_Employee.DiscardUnknown(m)
}

var xxx_messageInfo_Employee proto.InternalMessageInfo

func (m *Employee) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Employee) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Employee) GetEmployeeCode() string {
	if m != nil {
		return m.EmployeeCode
	}
	return ""
}

func (m *Employee) GetPhoneNumber() []*PhoneNumber {
	if m != nil {
		return m.PhoneNumber
	}
	return nil
}

type Provider struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TaxId                string         `protobuf:"bytes,2,opt,name=taxId,proto3" json:"taxId,omitempty"`
	Address              string         `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	PhoneNumber          []*PhoneNumber `protobuf:"bytes,4,rep,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Provider) Reset()         { *m = Provider{} }
func (m *Provider) String() string { return proto.CompactTextString(m) }
func (*Provider) ProtoMessage()    {}
func (*Provider) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{7}
}

func (m *Provider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Provider.Unmarshal(m, b)
}
func (m *Provider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Provider.Marshal(b, m, deterministic)
}
func (m *Provider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Provider.Merge(m, src)
}
func (m *Provider) XXX_Size() int {
	return xxx_messageInfo_Provider.Size(m)
}
func (m *Provider) XXX_DiscardUnknown() {
	xxx_messageInfo_Provider.DiscardUnknown(m)
}

var xxx_messageInfo_Provider proto.InternalMessageInfo

func (m *Provider) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Provider) GetTaxId() string {
	if m != nil {
		return m.TaxId
	}
	return ""
}

func (m *Provider) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Provider) GetPhoneNumber() []*PhoneNumber {
	if m != nil {
		return m.PhoneNumber
	}
	return nil
}

type PhoneNumber struct {
	CountryCode          string    `protobuf:"bytes,1,opt,name=countryCode,proto3" json:"countryCode,omitempty"`
	Number               string    `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	PhoneType            PhoneType `protobuf:"varint,3,opt,name=phoneType,proto3,enum=catalog.PhoneType" json:"phoneType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PhoneNumber) Reset()         { *m = PhoneNumber{} }
func (m *PhoneNumber) String() string { return proto.CompactTextString(m) }
func (*PhoneNumber) ProtoMessage()    {}
func (*PhoneNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{8}
}

func (m *PhoneNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneNumber.Unmarshal(m, b)
}
func (m *PhoneNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneNumber.Marshal(b, m, deterministic)
}
func (m *PhoneNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneNumber.Merge(m, src)
}
func (m *PhoneNumber) XXX_Size() int {
	return xxx_messageInfo_PhoneNumber.Size(m)
}
func (m *PhoneNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneNumber.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneNumber proto.InternalMessageInfo

func (m *PhoneNumber) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *PhoneNumber) GetPhoneType() PhoneType {
	if m != nil {
		return m.PhoneType
	}
	return PhoneType_WORK
}

type Commentary struct {
	Commentary           string               `protobuf:"bytes,1,opt,name=commentary,proto3" json:"commentary,omitempty"`
	Author               *Employee            `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	PostedOn             *timestamp.Timestamp `protobuf:"bytes,3,opt,name=postedOn,proto3" json:"postedOn,omitempty"`
	History              []*EditHistory       `protobuf:"bytes,4,rep,name=history,proto3" json:"history,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Commentary) Reset()         { *m = Commentary{} }
func (m *Commentary) String() string { return proto.CompactTextString(m) }
func (*Commentary) ProtoMessage()    {}
func (*Commentary) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{9}
}

func (m *Commentary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Commentary.Unmarshal(m, b)
}
func (m *Commentary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Commentary.Marshal(b, m, deterministic)
}
func (m *Commentary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commentary.Merge(m, src)
}
func (m *Commentary) XXX_Size() int {
	return xxx_messageInfo_Commentary.Size(m)
}
func (m *Commentary) XXX_DiscardUnknown() {
	xxx_messageInfo_Commentary.DiscardUnknown(m)
}

var xxx_messageInfo_Commentary proto.InternalMessageInfo

func (m *Commentary) GetCommentary() string {
	if m != nil {
		return m.Commentary
	}
	return ""
}

func (m *Commentary) GetAuthor() *Employee {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *Commentary) GetPostedOn() *timestamp.Timestamp {
	if m != nil {
		return m.PostedOn
	}
	return nil
}

func (m *Commentary) GetHistory() []*EditHistory {
	if m != nil {
		return m.History
	}
	return nil
}

type GetAllItemsResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Item                 *Item    `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	Error                *Error   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllItemsResponse) Reset()         { *m = GetAllItemsResponse{} }
func (m *GetAllItemsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllItemsResponse) ProtoMessage()    {}
func (*GetAllItemsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{10}
}

func (m *GetAllItemsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllItemsResponse.Unmarshal(m, b)
}
func (m *GetAllItemsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllItemsResponse.Marshal(b, m, deterministic)
}
func (m *GetAllItemsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllItemsResponse.Merge(m, src)
}
func (m *GetAllItemsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllItemsResponse.Size(m)
}
func (m *GetAllItemsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllItemsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllItemsResponse proto.InternalMessageInfo

func (m *GetAllItemsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetAllItemsResponse) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *GetAllItemsResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type GetItemsByTagResponse struct {
	Sucess               bool     `protobuf:"varint,1,opt,name=sucess,proto3" json:"sucess,omitempty"`
	Item                 *Item    `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	Error                *Error   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetItemsByTagResponse) Reset()         { *m = GetItemsByTagResponse{} }
func (m *GetItemsByTagResponse) String() string { return proto.CompactTextString(m) }
func (*GetItemsByTagResponse) ProtoMessage()    {}
func (*GetItemsByTagResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{11}
}

func (m *GetItemsByTagResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetItemsByTagResponse.Unmarshal(m, b)
}
func (m *GetItemsByTagResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetItemsByTagResponse.Marshal(b, m, deterministic)
}
func (m *GetItemsByTagResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetItemsByTagResponse.Merge(m, src)
}
func (m *GetItemsByTagResponse) XXX_Size() int {
	return xxx_messageInfo_GetItemsByTagResponse.Size(m)
}
func (m *GetItemsByTagResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetItemsByTagResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetItemsByTagResponse proto.InternalMessageInfo

func (m *GetItemsByTagResponse) GetSucess() bool {
	if m != nil {
		return m.Sucess
	}
	return false
}

func (m *GetItemsByTagResponse) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *GetItemsByTagResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type GetItemByIdResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Item                 *Item    `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	Error                *Error   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetItemByIdResponse) Reset()         { *m = GetItemByIdResponse{} }
func (m *GetItemByIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetItemByIdResponse) ProtoMessage()    {}
func (*GetItemByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{12}
}

func (m *GetItemByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetItemByIdResponse.Unmarshal(m, b)
}
func (m *GetItemByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetItemByIdResponse.Marshal(b, m, deterministic)
}
func (m *GetItemByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetItemByIdResponse.Merge(m, src)
}
func (m *GetItemByIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetItemByIdResponse.Size(m)
}
func (m *GetItemByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetItemByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetItemByIdResponse proto.InternalMessageInfo

func (m *GetItemByIdResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetItemByIdResponse) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *GetItemByIdResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type AddItemResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Item                 *Item    `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	Error                *Error   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddItemResponse) Reset()         { *m = AddItemResponse{} }
func (m *AddItemResponse) String() string { return proto.CompactTextString(m) }
func (*AddItemResponse) ProtoMessage()    {}
func (*AddItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{13}
}

func (m *AddItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddItemResponse.Unmarshal(m, b)
}
func (m *AddItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddItemResponse.Marshal(b, m, deterministic)
}
func (m *AddItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddItemResponse.Merge(m, src)
}
func (m *AddItemResponse) XXX_Size() int {
	return xxx_messageInfo_AddItemResponse.Size(m)
}
func (m *AddItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddItemResponse proto.InternalMessageInfo

func (m *AddItemResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AddItemResponse) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *AddItemResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type GetStockHistoryResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Item                 *Item    `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	Error                *Error   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStockHistoryResponse) Reset()         { *m = GetStockHistoryResponse{} }
func (m *GetStockHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*GetStockHistoryResponse) ProtoMessage()    {}
func (*GetStockHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{14}
}

func (m *GetStockHistoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStockHistoryResponse.Unmarshal(m, b)
}
func (m *GetStockHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStockHistoryResponse.Marshal(b, m, deterministic)
}
func (m *GetStockHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStockHistoryResponse.Merge(m, src)
}
func (m *GetStockHistoryResponse) XXX_Size() int {
	return xxx_messageInfo_GetStockHistoryResponse.Size(m)
}
func (m *GetStockHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStockHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStockHistoryResponse proto.InternalMessageInfo

func (m *GetStockHistoryResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetStockHistoryResponse) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *GetStockHistoryResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Error struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{15}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("catalog.PhoneType", PhoneType_name, PhoneType_value)
	proto.RegisterType((*Tags)(nil), "catalog.Tags")
	proto.RegisterType((*Tag)(nil), "catalog.Tag")
	proto.RegisterType((*Item)(nil), "catalog.Item")
	proto.RegisterType((*StockState)(nil), "catalog.StockState")
	proto.RegisterType((*Justification)(nil), "catalog.Justification")
	proto.RegisterType((*EditHistory)(nil), "catalog.EditHistory")
	proto.RegisterType((*Employee)(nil), "catalog.Employee")
	proto.RegisterType((*Provider)(nil), "catalog.Provider")
	proto.RegisterType((*PhoneNumber)(nil), "catalog.PhoneNumber")
	proto.RegisterType((*Commentary)(nil), "catalog.Commentary")
	proto.RegisterType((*GetAllItemsResponse)(nil), "catalog.GetAllItemsResponse")
	proto.RegisterType((*GetItemsByTagResponse)(nil), "catalog.GetItemsByTagResponse")
	proto.RegisterType((*GetItemByIdResponse)(nil), "catalog.GetItemByIdResponse")
	proto.RegisterType((*AddItemResponse)(nil), "catalog.AddItemResponse")
	proto.RegisterType((*GetStockHistoryResponse)(nil), "catalog.GetStockHistoryResponse")
	proto.RegisterType((*Error)(nil), "catalog.Error")
}

func init() { proto.RegisterFile("catalog.proto", fileDescriptor_0abbfcf058acdf89) }

var fileDescriptor_0abbfcf058acdf89 = []byte{
	// 932 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xdd, 0x6e, 0xdc, 0x44,
	0x14, 0x8e, 0x37, 0xfb, 0x7b, 0x36, 0x9b, 0xb6, 0x27, 0x25, 0x58, 0x4b, 0x95, 0x6e, 0xad, 0x0a,
	0xa5, 0x08, 0xb6, 0xd5, 0x02, 0xb9, 0x40, 0x95, 0x50, 0x13, 0x45, 0x21, 0x50, 0x9a, 0x6a, 0xba,
	0x52, 0xc5, 0xe5, 0xc4, 0x3e, 0x71, 0x06, 0xd6, 0x9e, 0x95, 0x67, 0x1c, 0xc5, 0x88, 0x6b, 0xae,
	0x79, 0x1e, 0x24, 0xc4, 0xd3, 0xf0, 0x0c, 0xdc, 0xa2, 0x19, 0xff, 0xac, 0x77, 0x93, 0x40, 0x2e,
	0x50, 0xee, 0x7c, 0xce, 0xf7, 0xcd, 0x39, 0xdf, 0xf9, 0x19, 0xdb, 0x30, 0xf0, 0xb9, 0xe6, 0x33,
	0x19, 0x8e, 0xe7, 0x89, 0xd4, 0x12, 0x3b, 0x85, 0x39, 0xfc, 0x28, 0x94, 0x32, 0x9c, 0xd1, 0x73,
	0xeb, 0x3e, 0x4d, 0xcf, 0x9e, 0x53, 0x34, 0xd7, 0x59, 0xce, 0x1a, 0x3e, 0x5e, 0x05, 0xb5, 0x88,
	0x48, 0x69, 0x1e, 0xcd, 0x73, 0x82, 0xf7, 0x31, 0x34, 0xa7, 0x3c, 0x54, 0xb8, 0x03, 0xeb, 0x9a,
	0x87, 0xae, 0x33, 0x5a, 0xdf, 0xed, 0x4f, 0x36, 0xc6, 0x65, 0xae, 0x29, 0x0f, 0x99, 0x01, 0xbc,
	0xc7, 0xb0, 0x3e, 0xe5, 0x21, 0xba, 0xd0, 0xd1, 0x3c, 0x7c, 0xc3, 0x23, 0x72, 0x9d, 0x91, 0xb3,
	0xdb, 0x63, 0xa5, 0xe9, 0xfd, 0xe1, 0x40, 0xf3, 0x58, 0x53, 0xf4, 0x5f, 0x91, 0x70, 0x04, 0xfd,
	0x79, 0x22, 0x83, 0xd4, 0xd7, 0x36, 0x4c, 0xc3, 0x86, 0xa9, 0xbb, 0x70, 0x13, 0x1a, 0x22, 0x70,
	0xd7, 0x47, 0xce, 0xee, 0x06, 0x6b, 0x88, 0x00, 0x9f, 0xc2, 0x40, 0x44, 0x3c, 0x24, 0x46, 0x4a,
	0xa6, 0x89, 0x4f, 0x6e, 0xd3, 0x9e, 0x59, 0x76, 0x22, 0x42, 0x53, 0x89, 0x9f, 0xc9, 0x6d, 0x59,
	0xd0, 0x3e, 0xe3, 0x33, 0x68, 0x29, 0xcd, 0x35, 0xb9, 0xed, 0x91, 0xb3, 0xdb, 0x9f, 0x6c, 0x55,
	0x6a, 0xde, 0x69, 0xe9, 0xff, 0xf4, 0xce, 0x40, 0x2c, 0x67, 0x78, 0x7f, 0x37, 0x00, 0x16, 0x5e,
	0x1c, 0x03, 0xca, 0x44, 0x84, 0x22, 0xe6, 0x33, 0xeb, 0x7d, 0x4d, 0x17, 0x34, 0xb3, 0x35, 0xb7,
	0xd8, 0x35, 0x08, 0x7e, 0x0a, 0x0f, 0xfc, 0x34, 0x49, 0x28, 0xd6, 0x35, 0x7a, 0xc3, 0xd2, 0xaf,
	0x02, 0xf8, 0x12, 0xfa, 0x33, 0xae, 0x34, 0x23, 0x65, 0x7c, 0xb6, 0xd4, 0xfe, 0x64, 0x38, 0xce,
	0x87, 0x35, 0x2e, 0x87, 0x35, 0x9e, 0x96, 0xc3, 0x62, 0x75, 0x3a, 0x3e, 0x82, 0x9e, 0x31, 0xdf,
	0x26, 0xa2, 0xe8, 0x45, 0x83, 0x2d, 0x1c, 0xf8, 0x15, 0xb8, 0x96, 0xf6, 0x9e, 0x0b, 0x2d, 0xe2,
	0x70, 0x2a, 0xf7, 0x89, 0x91, 0x4f, 0xe2, 0x82, 0x02, 0xdb, 0x9b, 0x16, 0xbb, 0x11, 0xc7, 0x97,
	0x30, 0xf8, 0x31, 0x55, 0x5a, 0x9c, 0x09, 0x9f, 0x6b, 0x21, 0xe3, 0xa2, 0x6f, 0xdb, 0x55, 0xdf,
	0xbe, 0xad, 0xa3, 0x6c, 0x99, 0x8c, 0x5f, 0xc2, 0x46, 0x2e, 0x43, 0x5e, 0x88, 0x80, 0x12, 0xb7,
	0x63, 0x0f, 0x3f, 0xa8, 0x0e, 0x97, 0x00, 0x5b, 0xa2, 0x79, 0xbf, 0x3b, 0x30, 0x58, 0x8a, 0x6b,
	0x46, 0xa9, 0xe9, 0x52, 0x17, 0x2b, 0x66, 0x9f, 0xf1, 0x33, 0xe8, 0x52, 0x34, 0x9f, 0xc9, 0x8c,
	0xf2, 0x9d, 0xa9, 0x07, 0x3e, 0x2c, 0x00, 0x56, 0x51, 0x70, 0x0f, 0xba, 0x73, 0xa9, 0x34, 0x05,
	0x27, 0xf1, 0x2d, 0xda, 0x5b, 0x71, 0x71, 0x0c, 0x9d, 0x73, 0xa1, 0xb4, 0x4c, 0x32, 0xb7, 0x69,
	0x37, 0xf8, 0xe1, 0x22, 0x4b, 0x20, 0xf4, 0x37, 0x39, 0xc6, 0x4a, 0x92, 0xf7, 0x03, 0xf4, 0x6b,
	0xfe, 0x6b, 0x95, 0xef, 0x41, 0xd7, 0xd4, 0x6b, 0x68, 0x85, 0xf2, 0x7f, 0x95, 0x52, 0x72, 0xbd,
	0xdf, 0x1c, 0xe8, 0x96, 0x95, 0x99, 0xc0, 0xf1, 0xe2, 0xd6, 0xd9, 0x67, 0x7c, 0x08, 0x2d, 0x8a,
	0xb8, 0x98, 0x15, 0x77, 0x28, 0x37, 0xd0, 0x83, 0x8d, 0xb2, 0x0b, 0x07, 0x32, 0x20, 0x5b, 0x7d,
	0x8f, 0x2d, 0xf9, 0x70, 0x0f, 0xfa, 0xf3, 0x73, 0x19, 0xd3, 0x9b, 0x34, 0x3a, 0xa5, 0xc4, 0x6d,
	0xad, 0x54, 0xfa, 0x76, 0x81, 0xb1, 0x3a, 0xd1, 0xfb, 0xd5, 0x81, 0x6e, 0x39, 0xb7, 0x9b, 0x24,
	0x69, 0x7e, 0x79, 0x1c, 0x94, 0x92, 0xac, 0x61, 0xde, 0x1a, 0x3c, 0x08, 0x12, 0x52, 0xaa, 0x50,
	0x53, 0x9a, 0xab, 0x42, 0x9a, 0xb7, 0x15, 0x92, 0x41, 0xbf, 0x86, 0x99, 0x77, 0x8a, 0x2f, 0xd3,
	0x58, 0x27, 0x99, 0x2d, 0x39, 0x57, 0x54, 0x77, 0xe1, 0x36, 0xb4, 0xe3, 0x3c, 0x47, 0xae, 0xac,
	0xb0, 0xf0, 0x05, 0xf4, 0x6c, 0xdc, 0x69, 0x36, 0xcf, 0x5b, 0xb5, 0x39, 0xc1, 0xe5, 0xf4, 0x06,
	0x61, 0x0b, 0x92, 0xf7, 0xa7, 0x03, 0x70, 0x20, 0xa3, 0x88, 0x62, 0xcd, 0x93, 0x0c, 0x77, 0x00,
	0xfc, 0xca, 0x2a, 0x32, 0xd7, 0x3c, 0xf8, 0x0c, 0xda, 0x3c, 0xd5, 0xe7, 0x32, 0xb9, 0x79, 0x6b,
	0x0b, 0xc2, 0x9d, 0xed, 0xec, 0x25, 0x6c, 0x1d, 0x91, 0x7e, 0x35, 0x9b, 0x99, 0xf7, 0xb5, 0x62,
	0xa4, 0xe6, 0x32, 0x56, 0x64, 0xa6, 0xa4, 0x52, 0xdf, 0x37, 0x53, 0x32, 0x65, 0x74, 0x59, 0x69,
	0xe2, 0x13, 0x68, 0x0a, 0x4d, 0x51, 0x51, 0xc1, 0xa0, 0x8a, 0x6e, 0xce, 0x33, 0x0b, 0xe1, 0x53,
	0x68, 0x51, 0x92, 0xc8, 0xa4, 0x10, 0xbe, 0xb9, 0x50, 0x60, 0xbc, 0x2c, 0x07, 0xbd, 0x4b, 0xf8,
	0xe0, 0x88, 0xb4, 0x4d, 0xbb, 0x9f, 0x99, 0x2f, 0x42, 0x99, 0x7b, 0x1b, 0xda, 0x2a, 0xad, 0xa5,
	0x2e, 0xac, 0xff, 0x33, 0xf3, 0x56, 0x91, 0x79, 0x3f, 0x3b, 0x0e, 0xee, 0xb2, 0x66, 0x0d, 0xf7,
	0x5e, 0x05, 0x81, 0x3d, 0x76, 0x87, 0x59, 0x7f, 0x81, 0x0f, 0x8f, 0x28, 0xff, 0xe4, 0x94, 0xf3,
	0xbf, 0xc3, 0xec, 0x5f, 0x43, 0xcb, 0xda, 0xe6, 0x53, 0x65, 0x3d, 0xd5, 0xb5, 0x6c, 0xb1, 0x85,
	0xc3, 0x28, 0x89, 0x48, 0x29, 0x1e, 0x96, 0xbf, 0x01, 0xa5, 0xf9, 0xc9, 0x13, 0xe8, 0x55, 0x97,
	0x0f, 0xbb, 0xd0, 0x7c, 0x7f, 0xc2, 0xbe, 0xbb, 0xbf, 0x86, 0x00, 0xed, 0xef, 0x4f, 0xf6, 0x8f,
	0x5f, 0x1f, 0xde, 0x77, 0x26, 0x7f, 0x35, 0xa0, 0x73, 0x90, 0x27, 0xc7, 0x23, 0xe8, 0xd7, 0x36,
	0x1a, 0xb7, 0xaf, 0x5c, 0x9b, 0x43, 0xf3, 0x4f, 0x34, 0x7c, 0x54, 0xa9, 0xbd, 0x66, 0xff, 0xbd,
	0xb5, 0x17, 0x0e, 0x1e, 0xc0, 0xe6, 0xd2, 0x82, 0x2a, 0x1c, 0xd4, 0xff, 0x60, 0xd4, 0x70, 0xa7,
	0x1e, 0xe2, 0xea, 0x22, 0xdb, 0x20, 0x87, 0x56, 0x4d, 0xb9, 0x6b, 0xb7, 0x53, 0xb3, 0xba, 0x99,
	0xde, 0x1a, 0x7e, 0x01, 0x9d, 0x62, 0x71, 0x70, 0x79, 0x14, 0x43, 0xb7, 0x32, 0x57, 0x36, 0xcb,
	0x5b, 0xc3, 0x13, 0xb8, 0xb7, 0x32, 0xf8, 0x1b, 0x05, 0x8c, 0xea, 0x02, 0xae, 0x5b, 0x15, 0x53,
	0xcd, 0x69, 0xdb, 0x9e, 0xfa, 0xfc, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfe, 0x6e, 0xdf, 0x09,
	0x80, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CatalogClient is the client API for Catalog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CatalogClient interface {
	GetAllItems(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (Catalog_GetAllItemsClient, error)
	GetItemsByTags(ctx context.Context, in *Tags, opts ...grpc.CallOption) (Catalog_GetItemsByTagsClient, error)
	GetItemById(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetItemByIdResponse, error)
	AddItem(ctx context.Context, in *Item, opts ...grpc.CallOption) (*AddItemResponse, error)
	//TODO: Update item
	GetStockHistory(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (Catalog_GetStockHistoryClient, error)
}

type catalogClient struct {
	cc *grpc.ClientConn
}

func NewCatalogClient(cc *grpc.ClientConn) CatalogClient {
	return &catalogClient{cc}
}

func (c *catalogClient) GetAllItems(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (Catalog_GetAllItemsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Catalog_serviceDesc.Streams[0], "/catalog.Catalog/GetAllItems", opts...)
	if err != nil {
		return nil, err
	}
	x := &catalogGetAllItemsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Catalog_GetAllItemsClient interface {
	Recv() (*GetAllItemsResponse, error)
	grpc.ClientStream
}

type catalogGetAllItemsClient struct {
	grpc.ClientStream
}

func (x *catalogGetAllItemsClient) Recv() (*GetAllItemsResponse, error) {
	m := new(GetAllItemsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *catalogClient) GetItemsByTags(ctx context.Context, in *Tags, opts ...grpc.CallOption) (Catalog_GetItemsByTagsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Catalog_serviceDesc.Streams[1], "/catalog.Catalog/GetItemsByTags", opts...)
	if err != nil {
		return nil, err
	}
	x := &catalogGetItemsByTagsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Catalog_GetItemsByTagsClient interface {
	Recv() (*GetItemsByTagResponse, error)
	grpc.ClientStream
}

type catalogGetItemsByTagsClient struct {
	grpc.ClientStream
}

func (x *catalogGetItemsByTagsClient) Recv() (*GetItemsByTagResponse, error) {
	m := new(GetItemsByTagResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *catalogClient) GetItemById(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetItemByIdResponse, error) {
	out := new(GetItemByIdResponse)
	err := c.cc.Invoke(ctx, "/catalog.Catalog/GetItemById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) AddItem(ctx context.Context, in *Item, opts ...grpc.CallOption) (*AddItemResponse, error) {
	out := new(AddItemResponse)
	err := c.cc.Invoke(ctx, "/catalog.Catalog/AddItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) GetStockHistory(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (Catalog_GetStockHistoryClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Catalog_serviceDesc.Streams[2], "/catalog.Catalog/GetStockHistory", opts...)
	if err != nil {
		return nil, err
	}
	x := &catalogGetStockHistoryClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Catalog_GetStockHistoryClient interface {
	Recv() (*GetStockHistoryResponse, error)
	grpc.ClientStream
}

type catalogGetStockHistoryClient struct {
	grpc.ClientStream
}

func (x *catalogGetStockHistoryClient) Recv() (*GetStockHistoryResponse, error) {
	m := new(GetStockHistoryResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CatalogServer is the server API for Catalog service.
type CatalogServer interface {
	GetAllItems(*empty.Empty, Catalog_GetAllItemsServer) error
	GetItemsByTags(*Tags, Catalog_GetItemsByTagsServer) error
	GetItemById(context.Context, *empty.Empty) (*GetItemByIdResponse, error)
	AddItem(context.Context, *Item) (*AddItemResponse, error)
	//TODO: Update item
	GetStockHistory(*empty.Empty, Catalog_GetStockHistoryServer) error
}

func RegisterCatalogServer(s *grpc.Server, srv CatalogServer) {
	s.RegisterService(&_Catalog_serviceDesc, srv)
}

func _Catalog_GetAllItems_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CatalogServer).GetAllItems(m, &catalogGetAllItemsServer{stream})
}

type Catalog_GetAllItemsServer interface {
	Send(*GetAllItemsResponse) error
	grpc.ServerStream
}

type catalogGetAllItemsServer struct {
	grpc.ServerStream
}

func (x *catalogGetAllItemsServer) Send(m *GetAllItemsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Catalog_GetItemsByTags_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Tags)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CatalogServer).GetItemsByTags(m, &catalogGetItemsByTagsServer{stream})
}

type Catalog_GetItemsByTagsServer interface {
	Send(*GetItemsByTagResponse) error
	grpc.ServerStream
}

type catalogGetItemsByTagsServer struct {
	grpc.ServerStream
}

func (x *catalogGetItemsByTagsServer) Send(m *GetItemsByTagResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Catalog_GetItemById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).GetItemById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catalog.Catalog/GetItemById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).GetItemById(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_AddItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Item)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).AddItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catalog.Catalog/AddItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).AddItem(ctx, req.(*Item))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_GetStockHistory_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CatalogServer).GetStockHistory(m, &catalogGetStockHistoryServer{stream})
}

type Catalog_GetStockHistoryServer interface {
	Send(*GetStockHistoryResponse) error
	grpc.ServerStream
}

type catalogGetStockHistoryServer struct {
	grpc.ServerStream
}

func (x *catalogGetStockHistoryServer) Send(m *GetStockHistoryResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Catalog_serviceDesc = grpc.ServiceDesc{
	ServiceName: "catalog.Catalog",
	HandlerType: (*CatalogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetItemById",
			Handler:    _Catalog_GetItemById_Handler,
		},
		{
			MethodName: "AddItem",
			Handler:    _Catalog_AddItem_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAllItems",
			Handler:       _Catalog_GetAllItems_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetItemsByTags",
			Handler:       _Catalog_GetItemsByTags_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetStockHistory",
			Handler:       _Catalog_GetStockHistory_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "catalog.proto",
}
